# Generated by Django 4.2.23 on 2025-09-27 10:13

import core.fields
import core.utils
import datetime
import dirtyfields.dirtyfields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySolutionsConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly name for this configuration (used in GraphQL and Admin)', max_length=100, unique=True)),
                ('hq_url', models.URLField(help_text='Base URL of Survey Solutions HQ (e.g., http://192.168.0.15:9700)')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('questionnaire_id', models.CharField(help_text='Questionnaire identity including version (e.g., GUID$3)', max_length=200)),
                ('questionnaire_title', models.CharField(blank=True, help_text='Cached title from HQ (e.g., Household Survey v3)', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Survey Solutions Config',
                'verbose_name_plural': 'Survey Solutions Configs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalPulledHistory',
            fields=[
                ('id', models.UUIDField(db_column='UUID', db_index=True, default=None, editable=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('paa_name', models.CharField(help_text="District display name (e.g., 'Kinondoni Municipal Council')", max_length=255)),
                ('district_code', models.CharField(help_text="District code used for matching (e.g., '0101')", max_length=20)),
                ('region_code', models.CharField(help_text="Region code used for matching (e.g., '01')", max_length=20)),
                ('questionnaire_id', models.CharField(help_text="Questionnaire identity (e.g., 'GUID$3')", max_length=200)),
                ('questionnaire_title', models.CharField(blank=True, help_text='Human-readable questionnaire title', max_length=500, null=True)),
                ('questionnaire_version', models.IntegerField(blank=True, help_text='Questionnaire version number', null=True)),
                ('export_job_id', models.CharField(blank=True, help_text='Survey Solutions export job ID', max_length=50, null=True)),
                ('export_started_at', models.DateTimeField(blank=True, help_text='When the HQ export job was initiated', null=True)),
                ('export_completed_at', models.DateTimeField(blank=True, help_text='When the HQ export job completed', null=True)),
                ('n_households_inserted', models.IntegerField(default=0, help_text='Number of new households (groups) inserted')),
                ('n_households_updated', models.IntegerField(default=0, help_text='Number of existing households (groups) updated')),
                ('n_individuals_inserted', models.IntegerField(default=0, help_text='Number of new individuals inserted')),
                ('n_individuals_updated', models.IntegerField(default=0, help_text='Number of existing individuals updated')),
                ('number_of_households', models.IntegerField(default=0, help_text='Total unique households affected (inserted + updated)')),
                ('matching_strategy', models.CharField(blank=True, help_text="How questionnaire was matched (e.g., 'code+name', 'name-only', 'manual-override')", max_length=50, null=True)),
                ('date_pulled', models.DateTimeField(blank=True, editable=False, help_text='When this ETL run was initiated')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', help_text='Status of the ETL run', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the run failed', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_created', models.ForeignKey(blank=True, db_column='UserCreatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_initiated', models.ForeignKey(blank=True, db_constraint=False, help_text='User who triggered this ETL run', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, db_column='UserUpdatedUUID', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Pulled Questionnaire History',
                'verbose_name_plural': 'historical Pulled Questionnaire History',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PulledHistory',
            fields=[
                ('id', models.UUIDField(db_column='UUID', default=None, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(db_column='isDeleted', default=False)),
                ('date_created', core.fields.DateTimeField(db_column='DateCreated', default=datetime.datetime.now, null=True)),
                ('date_updated', core.fields.DateTimeField(db_column='DateUpdated', default=datetime.datetime.now, null=True)),
                ('version', models.IntegerField(default=1)),
                ('paa_name', models.CharField(help_text="District display name (e.g., 'Kinondoni Municipal Council')", max_length=255)),
                ('district_code', models.CharField(help_text="District code used for matching (e.g., '0101')", max_length=20)),
                ('region_code', models.CharField(help_text="Region code used for matching (e.g., '01')", max_length=20)),
                ('questionnaire_id', models.CharField(help_text="Questionnaire identity (e.g., 'GUID$3')", max_length=200)),
                ('questionnaire_title', models.CharField(blank=True, help_text='Human-readable questionnaire title', max_length=500, null=True)),
                ('questionnaire_version', models.IntegerField(blank=True, help_text='Questionnaire version number', null=True)),
                ('export_job_id', models.CharField(blank=True, help_text='Survey Solutions export job ID', max_length=50, null=True)),
                ('export_started_at', models.DateTimeField(blank=True, help_text='When the HQ export job was initiated', null=True)),
                ('export_completed_at', models.DateTimeField(blank=True, help_text='When the HQ export job completed', null=True)),
                ('n_households_inserted', models.IntegerField(default=0, help_text='Number of new households (groups) inserted')),
                ('n_households_updated', models.IntegerField(default=0, help_text='Number of existing households (groups) updated')),
                ('n_individuals_inserted', models.IntegerField(default=0, help_text='Number of new individuals inserted')),
                ('n_individuals_updated', models.IntegerField(default=0, help_text='Number of existing individuals updated')),
                ('number_of_households', models.IntegerField(default=0, help_text='Total unique households affected (inserted + updated)')),
                ('matching_strategy', models.CharField(blank=True, help_text="How questionnaire was matched (e.g., 'code+name', 'name-only', 'manual-override')", max_length=50, null=True)),
                ('date_pulled', models.DateTimeField(auto_now_add=True, help_text='When this ETL run was initiated')),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='running', help_text='Status of the ETL run', max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Error message if the run failed', null=True)),
                ('json_ext', models.JSONField(blank=True, db_column='Json_ext', default=dict)),
                ('user_created', models.ForeignKey(db_column='UserCreatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_created', to=settings.AUTH_USER_MODEL)),
                ('user_initiated', models.ForeignKey(blank=True, help_text='User who triggered this ETL run', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(db_column='UserUpdatedUUID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(class)s_user_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pulled Questionnaire History',
                'verbose_name_plural': 'Pulled Questionnaire History',
                'ordering': ['-date_pulled'],
                'indexes': [models.Index(fields=['paa_name'], name='api_etl_pul_paa_nam_5ea8a2_idx'), models.Index(fields=['district_code'], name='api_etl_pul_distric_8b2afe_idx'), models.Index(fields=['date_pulled'], name='api_etl_pul_date_pu_7c94f2_idx'), models.Index(fields=['status'], name='api_etl_pul_status_3d0496_idx')],
            },
            bases=(dirtyfields.dirtyfields.DirtyFieldsMixin, core.utils.CachedModelMixin, models.Model),
        ),
    ]
