# Generated by Django 4.2.30 on 2026-06-10 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_etl', '0002_survey_dashboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveysolutionsconfig',
            name='hq_url',
            field=models.URLField(help_text='Base URL of Survey Solutions HQ (e.g., http://192.xxx.x.15:9700)'),
        ),
    ]
